[package]
name = "rs-utp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
log = "0.4"
tokio-util = { version = "0.7", features = ["codec"] }
thiserror = "2"
rand = "0.10"

[dev-dependencies]
env_logger = "0.11"
tokio-test = "0.4"
proptest = "1"